### ISSUE TITLE
Monitor keeps staying disconnected

### ISSUE THREAD

**Issue by Ninjiner** [jhillyerd/inbucket#103]
Hello I am using Inbucket now since half a year. (very nice software @jhillyerd )
Today I set nginx as a proxy before inbucket and deployed and SSL certificate from letsencrypt on it.
Since then if I try to enter the monitor, it wont connect and tells me, that it is disconnected.

I have been in this issue: https://github.com/jhillyerd/inbucket/issues/96
I copied the config for nginx and changed it for the letsencrypt use and removed the protection part.

Does anybody know what i am doing wrong?

**Comment by jhillyerd** [comment]
Did you keep the lines below?  I think they are what allow nginx to proxy websockets, which is what the monitor uses.

```
proxy_set_header    Upgrade          $http_upgrade;
proxy_set_header    Connection       "upgrade";
```

If you do have those lines, can you change "upgrade" to "Upgrade" and see if it has an effect?

**Comment by Ninjiner** [comment]
Jop that was the mistake. Somehow the got out of my proxy template. Thank you very much for your help.
