### ISSUE TITLE
Not able to install a package in Ubuntu 16.04

### ISSUE THREAD

**Issue by Nanthakumar-Gunasekaran** [jhillyerd/inbucket#104]
Hi,
I have been using Ubuntu 16.04. and I tried to install from packages using, 'sudo dpkg -i inbucket_VER_linux_amd64.deb'. But it always throwing an error saying "cannot access archive: No such file or directory".
Is there any other way to install inbucket from packages .?

**Comment by jhillyerd** [comment]
Hi, so you need to first download one of those packages (they aren't part of Debian or Ubuntu's repositories) from here: https://github.com/jhillyerd/inbucket/releases

When running the command, you will need to replace VER with the version you downloaded:

```
sudo dpkg -i inbucket_2.0.0_linux_amd64.deb
```
