### ISSUE TITLE
Respect the `INBUCKET_LOGLEVEL` parameter

### ISSUE THREAD

**Issue by kamusin** [jhillyerd/inbucket#108]
I was wondering how to decrease the amount of activity shown from the container, since the default value for `INBUCKET_LOGLEVEL` is `info`, I did managed to find that altering this to `error` should fit my needs,  however after modifying my docker service file didn't work. This is my current Service file (Ubuntu 16.04):

```
[Unit]
Description=Daemon for inbucket
After=docker.service
Wants=
Requires=docker.service

[Service]
Restart=on-failure
StartLimitInterval=20
StartLimitBurst=5
TimeoutStartSec=0
RestartSec=5
Environment="HOME=/root"
SyslogIdentifier=docker-inbucket
ExecStartPre=-/usr/bin/docker kill inbucket
ExecStartPre=-/usr/bin/docker rm  inbucket

ExecStart=/usr/bin/docker run \
        --net bridge -m 0b -e INBUCKET_LOGLEVEL=error \
 -p 8080:10080 \
 -p 25:10025 \
 --log-opt max-size=10m --log-opt max-file=5 \
        --name inbucket \
        jhillyerd/inbucket \

ExecStop=-/usr/bin/docker stop --time=0 inbucket
ExecStop=-/usr/bin/docker rm  inbucket

[Install]
WantedBy=multi-user.target
```

after restarting the Container I still see a lot of activity from this output which is related to INFO and WARN: 

```
2018/06/26 00:37:16 [INFO ] Inbucket dedd0ea (2017-12-27T07:20:16+0000) starting...
2018/06/26 00:37:16 [INFO ] HTTP templates mapped to "/opt/inbucket/themes/bootstrap/templates"
2018/06/26 00:37:16 [INFO ] HTTP static content mapped to "/opt/inbucket/themes/bootstrap/public"
2018/06/26 00:37:16 [INFO ] HTTP generating random cookie.auth.key
2018/06/26 00:37:16 [INFO ] SMTP listening on TCP4 0.0.0.0:10025
2018/06/26 00:37:16 [INFO ] Messages sent to domain 'bitbucket.local' will be discarded
2018/06/26 00:37:16 [INFO ] Retention configured for 72h0m0s
2018/06/26 00:37:16 [INFO ] HTTP listening on TCP4 0.0.0.0:10080
2018/06/26 00:37:16 [INFO ] POP3 listening on TCP4 0.0.0.0:10110
2018/06/26 00:39:03 [INFO ] SMTP Connection from 181.39.91.50:60274, starting session <1>
2018/06/26 00:39:03 [WARN ] SMTP[181.39.91.50]<1> Unrecognized command: AUTH
2018/06/26 00:39:04 [INFO ] SMTP[181.39.91.50]<1> Closing connection
```

what I expect, is to only see ERROR messages from this output, and not all the failed attempted connections from random people (in production this behaviour is more noisy of course). just for the record, the issue that we are trying to solve is decreasing the amount of activity  that is written in the log file, hopefully to the minimum.

Please let me know if I can help or provide you any other information you may need,
Cheers

**Comment by jhillyerd** [comment]
Based on the format of the log output (and the build date), I'm pretty sure you are running an older version of Inbucket - the current stable release was built in early May.  Pre-2.0, Inbucket used a configuration file instead of environment variables.

**Comment by kamusin** [comment]
shame on me, you are right. I pulled the latest image and works well. thanks!

**Comment by jhillyerd** [comment]
No worries.
