### ISSUE TITLE
helm chart using stable tag

### ISSUE THREAD

**Issue by zeidlermicha** [jhillyerd/inbucket#109]
Hey there, 

first off, thanks for such an awesome an helpful tool! 

when deploying the provided helm chart into kubernetes using the stable image from hub.docker.com the deployment (readiness and liveness probe) fails because the exposed ports where changed from 10080/10025/10110 to 9000/2500/1100.

Are you planing to provide a helm chart and docker image(tag) for v2.0.0? 

 If I can be of any assistance in that manner please let me know. I rather deploy the chart right from the source than maintain a custom chart in our repo.

**Comment by jhillyerd** [comment]
Thanks for the kind words.

You force me to disclose my dirty little secret: I don't use Kubernetes at all!  I'd love to get the helm charts updated for the stable release, but I expect there is quite some learning curve to it, plus I don't do much development during the N. hemisphere summer months.

@cpanato contributed the helm charts and may be able to provide some guidance for anyone interested in helping. See issue #97 for details.

Also worth noting I received an automated email with some suggested improvements: http://helmqa-zhaw-hendu.appuioapp.ch/charts/inbucket

**Comment by cpanato** [comment]
Hey!! 
the update the helm charts to the latest version is in my backlog, I just need to get used with the new release to understand what are the changes.

Lets to that, next week i will save some time to make this happen. sounds good?

**Comment by zeidlermicha** [comment]
ENVs actually translate quite well to helm. Either using them directly in the deployment description or injecting them by ConfigMap.

@cpanato I would suggest adding this option either way and giving the commented out examples in the values.yaml or adding a configmap.yaml template with default values. I already noticed env being read from Values.env in the deployment but no env variable was specified in the values.yaml file. So this might be the faster solution  

@jhillyerd I also noticed that there is no tag for version 2.0.0 in the hub.docker.com repository. I think that would be helpful for a default tag in the helm config for the new version. Otherwise using the stable tag might lead to problems in case of breaking changes in newer version tagged as stable as well.

**Comment by jhillyerd** [comment]
I started using the recommended vN.N.N tagging format on GitHub, looks like that broke the regex that was configured on the hub.  I've updated it, but I don't see a way to manually tag the existing release.  Is that something I have to do from the docker command line?

**Comment by zeidlermicha** [comment]
yes. tag the image manually on command line and than push it to docker hub.

**Comment by cpanato** [comment]
PR opened: https://github.com/helm/charts/pull/7126

it will be good to have a docker image with 2.0.0 (release-2.0) or something

**Comment by jhillyerd** [comment]
Assigning to myself as a reminder to add a release tag to docker hub.

**Comment by cpanato** [comment]
helm chart merged, we can close this issue

**Comment by jhillyerd** [comment]
Thanks for working on this!
