### ISSUE TITLE
how to custom domain for recevie mail?

### ISSUE THREAD

**Issue by bay1ts** [jhillyerd/inbucket#112]
use inbucket.org as default,send was refused,how to custom this domain?

**Comment by jhillyerd** [comment]
This depends on the mail server you are using (if inside a controlled network.)  If you were using postfix, then you could setup a transport rule to send all inbucket.org traffic to the IP address of your inbucket installation.

If you are on the public internet, then you would need to register your own domain, and setup an MX record to direct mail to that domain to the address of your inbucket server.

**Comment by bay1ts** [comment]
can I use ngrok get a tunnel to my pc?if can,which port should i use? 2500 or 1100?

**Comment by bay1ts** [comment]
![image](https://user-images.githubusercontent.com/6993315/44279557-68a7a480-a284-11e8-9ffa-cebac504944c.png)
![image](https://user-images.githubusercontent.com/6993315/44279569-71987600-a284-11e8-9ba4-948fcf8aa348.png)
then send an email to ccc@bushanweibo.com.didn't receive any thing. is there any problem?

**Comment by jhillyerd** [comment]
I haven't tried ngrok, but you will want to use the 2500 - that's the SMTP port, which is how mail is sent.  POP3 is only for reading mail from some mail clients.

Steps you'd need to take (roughly):

1. Setup forwarding from external IP X.X.X.X on port 25/TCP to inbucket host on port 2500
2. Register A record smtp.bushanweibo.com pointing to X.X.X.X
3. Register MX record @ for smtp.bushanweibo.com

You can delete the MX record for pop, not needed.

**Comment by bay1ts** [comment]
only need receive mail from others,don't need send.so,should i use 1100?If I don't understand it wrong, this project allows me to send an email to any address on my domain, I can receive it through the API.

**Comment by bay1ts** [comment]
Can I configure the program to listen directly to port 110?

**Comment by jhillyerd** [comment]
Trust me, 2500 is what you want.  Please do some research on SMTP and POP3, things will make more sense.

**Comment by jhillyerd** [comment]
Perhaps the easiest way to phrase it is that SMTP is the only way to get mail *into* Inbucket.  POP3 and REST are ways to get mail *out of* Inbucket.

And yes, you can configure Inbucket to use whatever port numbers you want.  Config info here: https://github.com/jhillyerd/inbucket/blob/master/doc/config.md

**Comment by bay1ts** [comment]
Thanks you very much,I will try it later

**Comment by bay1ts** [comment]
fixed,thanks
