### ISSUE TITLE
mailbox expires automatically

### ISSUE THREAD

**Issue by goxofy** [jhillyerd/inbucket#114]
Is it possible to set a expire time for the mailbox automatically, such as 10 minutes?
The mailbox will be automatically deleted  once the time expired.

**Comment by jhillyerd** [comment]
Yes, see retention period:  https://github.com/jhillyerd/inbucket/blob/master/doc/config.md#retention-period

It's per message, but once a mailbox is empty it is deleted.

**Comment by jhillyerd** [comment]
Inbucket doesn't track when a mailbox was created, only individual messages; it is not able to do this.

**Comment by goxofy** [comment]
OK thankyou
