### ISSUE TITLE
How will my actual application be able to send Emails to inbucket

### ISSUE THREAD

**Issue by rohitpatwari84** [jhillyerd/inbucket#115]
We have a application which sends emails via a service(that belongs to some security team) to whatever email we set via the UI . How then can I send emails to inbucket . I tried to ask my IT Team if they could set a autoforward rule in my microsoft exchange so that when my application sends email to me it gets routed to this local smtp server.But they are not agreeing to this ? Is there any other alternative ?

**Comment by jhillyerd** [comment]
Typically the email team would establish a rule in Exchange to route all mail to a particular hostname to inbucket; ie inbucket.myco.com

You might also look at having a test/staging version of the email service that sends all email to Inbucket.

**Comment by rohitpatwari84** [comment]
Hmm Thanks James...Actually first option -> My IT team is not supporting . They are telling me to directly read emails from microsoft web server .  2nd option -> Not possible as the Team is different and they will not agree to make such exceptions.

**Comment by jhillyerd** [comment]
Sorry, I don't have any other ideas.  Hope you are able to work something out.
