### ISSUE TITLE
Increasing disk usage with file storage

### ISSUE THREAD

**Issue by safaorhan** [jhillyerd/inbucket#116]
Hi, I run a high-traffic instance of inbucket. I realize sometimes, I have 100% disk utilization and need to manually delete inbucket file storage with rm -rf.

I'm trying to figure out the reason behind it, since the graph of disk usage does not peak in a day, but builds upon slowly by time.

![screen shot 2018-09-07 at 06 45 24](https://user-images.githubusercontent.com/4990386/45197486-45ac5700-b26a-11e8-976a-b0cc69d7c2d7.png)

This graph is strange to me, because my retention period is 24h.

Another strange thing I noticed is this:

![screen shot 2018-09-07 at 06 46 43](https://user-images.githubusercontent.com/4990386/45197563-a340a380-b26a-11e8-942e-d35645c4050d.png)

Last retention scan is 6 days ago (which is the time inbucket crashed and restarted itself) although my retention period is being 24h.

What am I missing here?

Can this be fixed by playing with INBUCKET_STORAGE_RETENTIONSLEEP config variable?

Thanks in advance

**Comment by jhillyerd** [comment]
Sorry to hear Inbucket crashed!  If you are ever able to repro, or have logs of it; do file a bug.  It's uptime should be measured in months. :)

I have previously encountered installations that were too busy for the retention scanner to keep up; and the 6 days since last scan is an indication of that.  INBUCKET_STORAGE_RETENTIONSLEEP is a good place to start, I'd set it to 0.

If mail is hot-spotting on some mailboxes, reducing INBUCKET_STORAGE_MAILBOXMSGCAP may also help - those are deleted at the time a new message is received, instead of waiting for the retention scanner to examine that mailbox.

I'll be the first to admit that the retention scanner is not a very efficient design.  Inbucket's file store does not keep any sort of central index, so the retention scanner has to examine each mailbox individually to do its job.  One day I'd like to implement a store on top of an embedded database (BoltDB or similar).

**Comment by safaorhan** [comment]
Hi again, after a closer investigation, I realized that the problem is the heavy traffic of mails.

Here is how I think the problem occurs:

Day by day the number of mails coming to my server is increasing. Up to some point the memory usage reaches to ~95% and higher. After that happens the retention scanner cannot work. So the mails in the storage starting to build up eventually reaching to 100% disk usage and crashing the inbucket instance.

So, I can close this issue. But before I want to ask another related question:

Is the memory utilization as high as expected in my case? Currently the memory usage is above 3GBs with a total of 400K retained mail and 10GB mail storage.

![screen shot 2018-10-11 at 22 30 31](https://user-images.githubusercontent.com/4990386/46829085-80dc0180-cda5-11e8-8c19-ef1325145958.png)
![screen shot 2018-10-11 at 22 30 39](https://user-images.githubusercontent.com/4990386/46829092-846f8880-cda5-11e8-899f-1a1db0c5b594.png)
![screen shot 2018-10-11 at 22 30 48](https://user-images.githubusercontent.com/4990386/46829096-876a7900-cda5-11e8-94aa-de2ef963ef01.png)

And is there any strategy to reduce memory usage? What is using this much memory? Incoming mails are retained in the memory for some time?

Thanks for your help 👍

**Comment by jhillyerd** [comment]
Inbucket should be very light on memory use, I've had older versions running for close to a year using only ~150MB of sysmem; but they were typically only handling a few concurrent connections and tens of thousands of messages per day.  http://demo.inbucket.org/status is lightly used, and only has 25MB after a month.

Inbucket does use memory while receiving and parsing MIME (I haven't profiled, but I think we use roughly double the size of the message while receiving.)  Do you think your instance has ~400MB of mail data in flight at any particular moment?  With MIME overhead and garbage collection, that would make a 1.4GB heap expected in my opinion.

Inbucket isn't doing any sort of caching such that the number of managed mailboxes would significantly impact the memory usage.  I don't remember exactly what info is stored by the retention scanning process while it is running, so perhaps it is consuming a lot.

There could still be a memory leak somewhere, but it would be difficult to know without being able to stop traffic to your instance to see if it shrinks down to a reasonable size.

**Comment by jhillyerd** [comment]
Also, Inbucket exposes Go's standard debugging vars at `/debug/vars` - there may be some tools than can monitor these over time and help you understand how quickly memory use is growing.

**Comment by safaorhan** [comment]
If you give me a detailed instruction set, I can profile and give you the results.

I'm not a go developer so, take your time to explain 😁

**Comment by jhillyerd** [comment]
It looks like I will need to add pprof support to Inbucket before we can do any profiling of a running instance, filed #120 to track that effort.

**Comment by jhillyerd** [comment]
I've added the profiling support, now available in https://github.com/jhillyerd/inbucket/releases/tag/v2.1.0-beta1

To use it, you will need to run with environment `INBUCKET_WEB_PPROF=true` (if you do not have the web UI behind a firewall, I would not recommend leaving Inbucket in that mode, as it would be easy to denial-of-service attack your instance by requesting repeated traces).

Once you see high memory usage (anything over 500MB), download a heap profile:

`curl http://127.0.0.1:9000/debug/pprof/heap --output heap.pprof`

(you can use wget or even a web browser, but make sure to update the IP/port for your inbucket)

Then ZIP the file up and attach here.  If you want to see the contents of the file before you send it, install Go 1.11.1 and run:

`go tool pprof -http :8080 ./heap.pprof`

and point a web browser at http://localhost:8080/ - the flame graph is the easiest to read.
