### ISSUE TITLE
utf8 in sender name not shown correctly

### ISSUE THREAD

**Issue by SpikePy** [jhillyerd/inbucket#117]
Version:1.2.0-rc1

When reciving a mail from the sender "XLT-äéßsvu XLT-äéßy" with the mail address qa_1539156208516@bof.de he is shown in inbucket monitor and mail as "=?utf-8?q?XLT-=C3=A4=C3=A9=C3=9Fw_XLT-=C3=A4=C3=A9=C3=9Ftfucuui?= <qa_1539156208516@bof.de>"

![image](https://user-images.githubusercontent.com/16565183/46719938-74ee2380-cc6f-11e8-893c-05157b8afd8a.png)

While sending the mail to outlook shows the senders name correctly.

**Comment by jhillyerd** [comment]
1.2.0-rc1 is outdated, and I believe this has been fixed somewhere along the line.  Please test on 2.0.0

**Comment by SpikePy** [comment]
Installed 2.0.0 but bug is still present

**Comment by jhillyerd** [comment]
Interesting.  One other question, after installing 2.0, did you re-send the mail or just view mail that had been received by 1.2?  We should be converting these during the delivery process, not during the display process.

**Comment by SpikePy** [comment]
Even after resending the mail the problem persists.

**Comment by jhillyerd** [comment]
Thanks for checking.  I think Inbucket needs some end-to-end testing to catch this sort of thing.  Will see if I can get to the bottom of it.

**Comment by jhillyerd** [comment]
Integration test suite completed in #119 - will write a test for this now.

**Comment by jhillyerd** [comment]
Now available in https://github.com/jhillyerd/inbucket/releases/tag/v2.1.0-beta1
