### ISSUE TITLE
README: Add link to Go REST client docs

### ISSUE THREAD

**Issue by jhillyerd** [jhillyerd/inbucket#123]
No easy way to see REST API docs.

**Comment by rmoswela** [comment]
Hey, which REST API docs are you talking about?

**Comment by jhillyerd** [comment]
https://godoc.org/github.com/jhillyerd/inbucket/pkg/rest/client - they could probably be reviewed and expanded upon, maybe include an example.

**Comment by jhillyerd** [comment]
Fixed in 469132fe2fe5ff2aad0138245d45cf0de42fa446
