### ISSUE TITLE
Thanks for amazing service! I prepared simple js client

### ISSUE THREAD

**Issue by Xotabu4** [jhillyerd/inbucket#131]
Thanks for developing and supporting this service.
I prepared simple js-client - https://github.com/Xotabu4/inbucket-js-client
It might have bugs, so will be thankful for feedback!

**Comment by jhillyerd** [comment]
Cool, thanks for that.  Does this work both in browser and with nodejs?  I can add it to the wiki page if you like.

**Comment by Xotabu4** [comment]
@jhillyerd i using it now in nodejs testing projects, and haven't tested it in browser.

**Comment by jhillyerd** [comment]
Cool.  Listed here now: https://github.com/jhillyerd/inbucket/wiki/REST-API
