### ISSUE TITLE
Design limits handling large mailing lists

### ISSUE THREAD

**Issue by serussell** [jhillyerd/inbucket#23]
The design of inbucket means that inbucket keeps a file handle open for every mailbox that it is delivering mail to until it's done processing the email.  The result is that large mailing lists can run the process out of file handles before email processing is finished, causing some mail to not be delivered into some mail boxes.

**Comment by serussell** [comment]
Thanks!

**Comment by jhillyerd** [comment]
No problem, sorry it took so damn long. ;)
