### ISSUE TITLE
Create Homebrew Formula for Inbucket

### ISSUE THREAD

**Issue by jhillyerd** [jhillyerd/inbucket#30]
Many web developers use OS X, and install their dependencies via Homebrew.  Inbucket would be more attractive if it had a Homebrew Formula and optionally started at boot.

http://brew.sh/

**Comment by jhillyerd** [comment]
It may make sense for the initial formula to just install pre-compiled binaries - https://github.com/Homebrew/homebrew-binary

**Comment by jhillyerd** [comment]
This is much better base: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/consul.rb

**Comment by jhillyerd** [comment]
Now working for --HEAD c421e4e0ebf2013b2cc7aa15f900ee7376cc0c74

How to test it: https://github.com/jhillyerd/inbucket/wiki/Homebrew-Test

**Comment by tommywo** [comment]
@jhillyerd https://raw.githubusercontent.com/jhillyerd/inbucket/feature/brew/etc/homebrew/inbucket.rb 
returns 'not found'

**Comment by jhillyerd** [comment]
This is in a state of flux...  the formula will be part of the rc3 release, but since I've completed it, it's branch has been merged into the develop branch.

I've updated the wiki to refer to develop https://github.com/jhillyerd/inbucket/wiki/Homebrew-Test - but I don't have a Mac here to test with right now.

**Comment by jhillyerd** [comment]
It looks like building a "tap" for inbucket is the way to go:

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md

**Comment by jhillyerd** [comment]
That was easy!  https://github.com/jhillyerd/homebrew-inbucket
