### ISSUE TITLE
identify mailbox by full email, including domain

### ISSUE THREAD

**Issue by tommywo** [jhillyerd/inbucket#33]
(continued from  #31)
- you cant search for 'user@gmail.com'
- mailbox is identified only by username, but not domain, so mail to user@gmail.com and user@yahoo.com will go to one mailbox 'user'

So i think it would be better to identify mailbox by complete email, and get rid of '@inbucket' by the 'View' button.

**Comment by jhillyerd** [comment]
This would probably be best as an opt-in feature, as it would significantly impact existing users.  I imagine it having 3 modes:

1. **Hard Mailbox Only** - Domain information is ignored on the SMTP side, and flagged as an error in Web UI and REST API. (Matching functionality in 1.0, 1.1)
2. **Soft Mailbox Only** - Domain information is ignored on the SMTP side, and also ignored in Web UI and REST API.  (james@gmail.com == james@hotmail.com)
3. **Mailbox & Domain** - Domain information is normalized and respected in SMTP, Web UI and REST API.

**Comment by jhillyerd** [comment]
Merged into develop branch; is working for all the tests I can think of.  Since Inbucket doesn't have an integration test suite, there are problem some bugs somewhere.
