### ISSUE TITLE
Add support to redirect email by replacing the recipients

### ISSUE THREAD

**Issue by BrendanBall** [jhillyerd/inbucket#40]
This is a specific feature I require for an email development server.
Use case: Need to test email in outlook webapp and I can't make an account for every random recipient that I want to test for. Currently we have to change the data to point to a specific account however this is undesirable for a proper development environment.
My solution is to point my application to an email dev server that will replace all incoming mail recipients with a configured email address (I'm usually more interested in the contents of email than the recipients, but we can add the original recipients somewhere in the email for reference, maybe the subject).
This would also come in useful for when testing on a desktop client with pop3 to prevent having to create an account for every email address that we need to test. The webui is nice, but we often need to test email in a specific client to make sure it is formatted correctly. 

To complete this it would require a separate issue that allows forwarding emails to another smtp server, however I won't create that issue unless you're interested in having this feature integrated into the codebase.

This would use a feature flag, ie. only use this feature if the developer wants it.
No current functionality should need to be broken to support this feature.

Not sure if anyone else has a need for this, but I would create a PR for this if anyone's interested.

**Comment by jhillyerd** [comment]
I'm pretty sure people would be interested in this.  I know one installation has an external server that traps email from specific hosts, and forwards it to a particular Inbucket mailbox.

I would want it very clear in the configuration what this and any sort of forwarding functionality does, as I consider it important that Inbucket keeps email within a network.  I wouldn't be in favor of adding any sort of selective routing, etc.

**Comment by BrendanBall** [comment]
I would see this functionality as being off by default. Can you elaborate on the selective routing please? I would see the functionality of replacing recipients in an email with a configured recipient to be done in some kind of middleware, keeping it separate from the smtp insides. The installation you're referring to sounds like what I want, except I'd preferably not want to run multiple layers of email dev servers to accomplishment the functionality, ie. I want to run a single Docker container, thus the need to add this functionality to inbucket.

Also, replacing recipients with a configured recipient is quite a separate issue to forwarding mail to another (specified) smtp server. Would you want me to create a separate issue for that or keep it all here?
I think adding some kind of support for pluggable middleware would be great to be able to add dev environment specific functionality as everyone requires different features to enhance their dev environment.

**Comment by jhillyerd** [comment]
I think you are right, a middleware layer is a good way to handle this type of stuff.  It may be tricky to implement given that Inbucket wasn't designed with that in mind, although I did try to use interfaces where possible with the thought of switching out the datastore someday.

Seems like we'd need a way to intercept messages prior to being placed into the datastore (for rewriting) at minimum, and perhaps a way to act on them after (for forwarding).  Messages are meant to be immutable after Close() is called.

a939605d4a17d2b77b488f0ceb6ac3c0a533e241 would help here, since it keeps the code that creates, writes and closes a message together.

I've created a feature branch if you want to take a stab at a middleware system, file PRs against: https://github.com/jhillyerd/inbucket/tree/feature/middleware

**Comment by BrendanBall** [comment]
awesome, disclaimer: I'm brand new to Go so might take me a while before anything is done. Should be fun though given that inbucket wasn't designed with middleware in mind :P

**Comment by jhillyerd** [comment]
No worries, Inbucket was my first real project in Go - I've done quite a bit of refactoring, but I'm sure there is plenty of ugly code in there. :)  Feel free to +me on commits to your repo if you want comments before creating a PR, or just email me.

**Comment by BrendanBall** [comment]
I haven't had a chance to work on this. I'm more focused on other things so I don't really need this functionality at the moment. Unless someone wants this functionality and wants to take on this issue we can probably close it.

**Comment by jhillyerd** [comment]
Thanks for the update, no worries.  Timing is good as I'm planning to do a lot of modernization/refactoring to the codebase for 1.3 - it's messy and I didn't know Go well when I wrote most of it.  This would probably have broken any work you had.

Waiting for Go 1.9 would also be good for any extension plans, as Go 1.8 will only support dynamic module loading on Linux.
