### ISSUE TITLE
FROM address local part length limited to 64 characters

### ISSUE THREAD

**Issue by avuori** [jhillyerd/inbucket#41]
Mailgun - inbucket communication is difficult with this limitation because Mailgun adds metadata to FROM address and makes the local part exceed 64 characters.

Limitation is located in smtpd/utils.go.

According to our testing, allowing 128 characters resolves this problem.

**Comment by jhillyerd** [comment]
I was following RFC3696 when I implemented the 64 character limit, but it sounds like it is out of date:

http://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address

If you'd like to submit a PR, please do it against the develop branch - and add a case to the relevant test table.  If not, I'll look at this when I have a chance.

**Comment by jhillyerd** [comment]
Actually, I think I am reading that stack-overflow wrong.  Seems like Mailgun is in the wrong here.  We can still have Inbucket accept more though, no big deal.

**Comment by jhillyerd** [comment]
Fix is now available in develop branch.  The overall limit of 320 chars is still in place, let me know if we need to bump that up too.
