### ISSUE TITLE
how can I send email using sendmail ?

### ISSUE THREAD

**Issue by cpanato** [jhillyerd/inbucket#42]
Hello

How I can send an email to the inbucket using the sendmail ?

thanks

**Comment by jhillyerd** [comment]
I haven't used sendmail in a long time, but I believe it needs to use Inbucket as its "smart host", see:

https://support.appriver.com/kb/a242/configuring-smart-host-service-in-sendmail.aspx

**Comment by cpanato** [comment]
didnt work :s 

what is the scenario
I have my application running on docker and I set it up a docker-compose to include the inbucket and link that to my app.

then I modify the sendmail.mc to add the smart host but didnt work.

if I do a telnet in the docker app and sent the example message I go the message. however if I sent an email from my app it not get it. :(

**Comment by cpanato** [comment]
i made it work :)

need set the port as well

define(`SMART_HOST',`hostname)dnl
define(`RELAY_MAILER',`esmtp')dnl
define(`RELAY_MAILER_ARGS', `TCP $h 10025')dnl
