### ISSUE TITLE
Go Client for REST API

### ISSUE THREAD

**Issue by cpanato** [jhillyerd/inbucket#43]
Hello

this project have a Go driver? then I can use to integrate with my go project? for testing?

thanks

**Comment by jhillyerd** [comment]
We don't have any drivers at the moment.  Are you looking for a way to send mail to Inbucket with Go or a way to access the REST API with Go?

**Comment by cpanato** [comment]
access the REST API.
thanks for the response :)

**Comment by cpanato** [comment]
will be very useful :)

**Comment by jhillyerd** [comment]
Okay, I will take a look at doing this.  At the very least, I could move the JSON structs to their own package so that they can be easily imported into another project without bringing the rest of Inbucket with them.

**Comment by tommywo** [comment]
@jhillyerd Actually, I created [java client/driver for inbucket](https://github.com/stepstone-tech/inbucket-java-client), so we have at least one driver. :)

**Comment by jhillyerd** [comment]
@tommywo Cool, I will link it from the Wiki.

**Comment by jhillyerd** [comment]
Ok, [REST API](https://github.com/jhillyerd/inbucket/wiki/REST-API) wiki now has a link to the stepstone-tech java driver.

I've also extracted the JSON files into their own package: https://github.com/jhillyerd/inbucket/blob/develop/rest/model/apiv1_model.go

Next step is to create a lightweight Go client.
