### ISSUE TITLE
Add list-all-mails function in WebUI

### ISSUE THREAD

**Issue by Luzifer** [jhillyerd/inbucket#44]
In order not to search for the mailbox containing mails (or even worse trying to find the hash in a hash database) when you do not want to remember which addresses had mails sent to, please allow either a list of mailboxes containing more than zero mails or allow a wildcard in the mailbox name.

Though it's a bit lazy I'm not able to remember which addresses do have mails sent to but I eventually need to look at those mails. Having the data store metric "Currently Retained: 15" I know there are messages and I could take a look into the filesystem to identify those 15 mails but having a UI method to list those messages either by a list of mailboxes or a `*` search returning all 15 mails as if they were in a single mailbox would be way more convenient.

**Comment by jhillyerd** [comment]
I agree this would be useful.  The difficulty right now is that it would be a very expensive operation for a large installation, as Inbucket would have to walk the directory tree and inspect each mailbox.  At some point I'd like to use a native Go database (like boltdb) to index all email and make this easy to implement.  It would also improve the efficiency of the retention system, as that can take many minutes to complete with millions of emails.

As a temporary hack, the retention scanner could compile an in-memory list of mailboxes containing mail.

My work on Inbucket is on hold for a bit, I've been focusing on revamping https://github.com/jhillyerd/enmime (which Inbucket depends on).  Once that's stable I'll starting chipping away at Inbucket again.

**Comment by cardonator** [comment]
For my use case this would also be extremely helpful. Our devs are constantly trashing and restarting their inbucket instances but the only way to see where emails are going is to look at the inbucket docker logs if they don't know already (and often don't).

Your temporary hack (which I would alternatively call "the simplest solution for this request") would work perfectly for us.

**Comment by jhillyerd** [comment]
Something else I had considered was to add a websocket & UI for monitoring deliveries real time.  Inbucket could also cache a configurable number of deliveries to replay to fresh websocket connections.

I think it would be cleaner than the aforementioned hack.  The downside would be that the cache would be lost if Inbucket is restarted.  @Luzifer & @cardonator - how would that perform under your use cases?

**Comment by cardonator** [comment]
That would work great for me as long as you can easily see from the UI what inboxes received mails since the last startup. Like I said, our devs are constantly trashing their docker instances and rarely care about any more than the last few emails.

**Comment by jhillyerd** [comment]
@cardonator - Yeah, I was thinking it would list a timestamp, from, mailbox, and subject line - and you could click on it to go directly to that message.

**Comment by cardonator** [comment]
That would be awesome.

**Comment by jhillyerd** [comment]
Almost done, it's working now.  Just need to add some configuration options to control how much history is kept, and the option to disable the UI.  (Yay, security through obscurity!)

**Comment by jhillyerd** [comment]
@cardonator Monitor feature has been merged into the develop branch.  If anyone over there wants to test and you are using my docker images, grab: jhillyerd/inbucket:latest

**Comment by cardonator** [comment]
I can easily test this on Monday. To clarify, the "latest" tag on Dockerhub has the develop branch built in it?

**Comment by jhillyerd** [comment]
@cardonator Yes, that's correct.  I have the build hooks setup such that inbucket:stable tracks master and inbucket:latest tracks develop.

There aren't any other major projects planned for this release of Inbucket, so I think develop should remain usable through the release of 1.2.0.  When I release the beta for 1.2.0, it will push to master.

**Comment by cardonator** [comment]
@jhillyerd we rolled this out in our dev environment and had several people testing with it. It looks and works great, good work!

**Comment by jhillyerd** [comment]
@cardonator that's great to hear, thanks for testing it!
