### ISSUE TITLE
Feature: Add domain "whitelist" parameter

### ISSUE THREAD

**Issue by Luzifer** [jhillyerd/inbucket#51]
Instead of having a blacklist `domain.nostore` it would be great to have a whitelist (`domain.dostore`?) which, if set, rejects all mails not having a recipient on that domain(s).

**Use-Case:** I'm using Inbucket as a single-purpose-mailbox SMTP server for those "enter your email address to get your download link sent to you - and well, we will spam you with newsletters afterwards"-things… Sadly spammers seem to think this SMTP will redirect their messages to whomever they want… Having all that crap not using my domain rejected would be great…

![image](https://user-images.githubusercontent.com/20142/27636999-589d6b8c-5c0e-11e7-83c1-89d9047c1a08.png)

**Comment by jhillyerd** [comment]
Ah, I guess Inbucket looks like an open relay to them.

I wonder if it's better to have it actually reject the mail so it doesn't appear as an open relay, or just silently drop it.  The former might be a bit more work to implement, but may reduce the amount of traffic you get.

**Comment by jhillyerd** [comment]
I ended up taking a slightly different strategy, you can set a default accept/reject policy and then specify exceptions.  Same for store/nostore.

**Comment by Luzifer** [comment]
I like the solution you've built! Will test it as soon as it's in the next release! Thank you very much for implementing it! 🙂
