### ISSUE TITLE
Basic authentication

### ISSUE THREAD

**Issue by CW-007** [jhillyerd/inbucket#53]
Introduce basic authentication to prevent unauthorized access to the web application on a corporate network.

**Comment by jhillyerd** [comment]
I view this as a slippery slope... first people want a password, then they want multiple users accounts, then they want accounts tied to individual mailboxes, LDAP integration, SAML, etc.  Then I'd have to offer similar protection to the web API, and POP3 interfaces.  I'm not interested in adding or supporting any of that.

Installations that need to be protected can be run behind a reverse-proxy.  This can be accomplished with apache or nginx.
