### ISSUE TITLE
Clear button does not work on Monitor page

### ISSUE THREAD

**Issue by CW-007** [jhillyerd/inbucket#54]
When retention.minutes=0 is set, the Clear button does not have a lasting effect.

The list of messages is momentarily cleared, but when the page is reloaded, the list of messages is repopulated.

Using the API to clear a mailbox also does not clear the Monitor page.

**Comment by jhillyerd** [comment]
This is working as designed; think of the monitor like a log file.  The use cases I envisioned for the monitor:

1. I am about to perform an action I expect to generate mail (perhaps to random inboxes), and want to see what is delivered to Inbucket:
    * I open the monitor tab
    * Click clear
    * Perform mail generating action
    * Observe results
2. I was expecting a message to show up, but it didn't.  I can hop over to the monitor tab and see the last N (default 30) messages to confirm I'm looking at the correct mailbox.
3. I've had the monitor open for a long time and there are too many entries in my browser window, I can click clear to refresh.

Inbucket is designed to support multi-user installations, so one user should not be able to clear the log for another.

You can control the number entries remembered by the server here:

https://github.com/jhillyerd/inbucket/blob/master/etc/inbucket.conf#L108
