### ISSUE TITLE
Can I use inbucket as a mail server like sendmail ?

### ISSUE THREAD

**Issue by goodforever** [jhillyerd/inbucket#57]
Can I use inbucket as a mail server like sendmail ?

**Comment by jhillyerd** [comment]
It really depends what you are trying to do.  If you want it to relay messages out to the internet, then no.  Inbucket is designed to soak up all mail sent to it, preventing leaks of dev/test messages to external users.

If you want your local applications to send to a mail server for you to read in our web interface, then yes.
