### ISSUE TITLE
Feature: Flag Mails as read

### ISSUE THREAD

**Issue by SpikePy** [jhillyerd/inbucket#58]
If you open a mailbox in the web interface to see all its mails there is no indicator on which mails have already been read. 

It would be nice if you could add such a feature by adding an attribute "read" that equals to false/true OR add another class as indicator. Using a class you could also add a css-rule that prints the Header of an unread message bold.

![Example with added class](https://user-images.githubusercontent.com/16565183/32487111-05f021e2-c3a9-11e7-9af1-6bf56269d93d.png)

**Comment by jhillyerd** [comment]
Seems feasible.  Would need to be added to smtpd.Message interface, implemented in in filestore, then plumbed into web UI.

**Comment by jhillyerd** [comment]
Bumping to 1.3 since this would require a datastore wipe of existing installs.

**Comment by SpikePy** [comment]
Can you also extend the API with this flag, so that you are able to request for unread/read mails?

**Comment by jhillyerd** [comment]
Looking at the REST API, it doesn't support any other query uses, so I don't see a reason to add seen.  The message metadata is pretty small, and now contains a `seen` boolean.
