### ISSUE TITLE
Migrate to multi-stage docker build

### ISSUE THREAD

**Issue by jhillyerd** [jhillyerd/inbucket#66]
Using a multi-stage build would reduce the size of our container image, and should allow most of the build to be scripted in the Dockerfile instead of bash.

https://docs.docker.com/engine/userguide/eng-image/multistage-build/

**Comment by jhillyerd** [comment]
Tested this out on fauxmailer: https://github.com/jhillyerd/fauxmailer/blob/master/Dockerfile

Main caveat is that you need to use the same distro for the build and run images; cannot build in golang then run in alpine.

**Comment by Luzifer** [comment]
> cannot build in golang then run in alpine.

You can build in `golang:alpine` and then run in `alpine`… (Also if you don't need cgo you can build using `CGO_ENABLED=0` which enables you to build static binaries and you don't need to care about the glibc / libmuslc foo…)
