### ISSUE TITLE
Friendly URL

### ISSUE THREAD

**Issue by speendo** [jhillyerd/inbucket#73]
First of all, thank you for Inbucket!

It is so(!) great to finally have some sort of mailinator on my own server running. Awesome!

Using it only a couple of days, I have found some feature requests. Some of them might be pointless or due to my lack of knowledge on how to use inbucket correctly. Sorry for that.

But here's my first feature request:

It would even raise productivity, if you could directly enter an inbox with `<inbucket-url>/<inbox-name>`.

Like, if you would want to see emails for user foo, you could enter the mailbox maybe with `https://inbucket.yourdomain.tld/foo/`.

**Comment by jhillyerd** [comment]
It looks like the gorilla.mux router we use will process URL routes in the order they are defined, so we could probably accomplish this quite easily.
