### ISSUE TITLE
Manual: explain how to configure postfix to use a subdomain

### ISSUE THREAD

**Issue by speendo** [jhillyerd/inbucket#75]
This is of course not part of Inbucket itself. However, being not very experienced with email servers, I had a hard time to configure my mail server to receive and forward mail dedicated to be managed by inbucket.

I guess most people have a similar setup like me: A Debian based linux server with postfix running the mailboxes. I also would assume most people want something similar like I did: configure a subdomain to be used for potential spam mail.

Of course it's difficult to find a starting point: some people might need to first install and configure postfix or setup a subdomain on their DNS. I wouldn't explain that.

However, long story short, [Kotunio](https://serverfault.com/users/451913/kotoniu) helped me a lot with this answer on [serverfault](https://serverfault.com/): https://serverfault.com/a/892074/288202 - I think something like this would be appreciated in the installation manual.

**Comment by jhillyerd** [comment]
I'm not sure if there is a setup common to *most people*.  But at a previous employer I did use Inbucket behind a postfix w/ transport_maps like your serverfault answer recommends.

These type of docs seems like a good candidate for Wiki pages, if you'd like to contribute one (and GitHub lets us do that).  Otherwise you could paste here and I will create page.

**Comment by speendo** [comment]
Yes, I am definitely willing to do that. However, as I said, I am very inexperienced with email servers, so it could be that my writing turns out to be gibberish in the end...

**Comment by speendo** [comment]
Rebuilding my mail server and bumping into the same problem again, I realized, I didn't keep my promise to write a wiki page. Sorry for this.

Worse than that, my new mail server works with mailcow, changing the necessary steps, so I am still not able to write a good wiki page.

However, I can (and will) write a page on how to do it with mailcow.

(As I'm really not a mail expert, I hope my writing is not too bad).

**Comment by jhillyerd** [comment]
Even pasting some sample configuration into a bug could be helpful. I was thinking about starting an inbucket-examples repo with docker-compose configurations for things like fronting inbucket with another mailserver, or putting it behind another HTTP server.
