### ISSUE TITLE
Forward mails with <buzzword> in the email title

### ISSUE THREAD

**Issue by speendo** [jhillyerd/inbucket#76]
I don't think this feature request is easy to implement - as far as I know inbucket doesn't have mail sending capabilities yet... However, I still would like to leave that here:

It would be nice to have mailboxes that handle all mail as trash, except if there is a certain buzzword in the mail title. In this case the mail should be forwarded to the owner of the mailbox.

When would you need this?  
Let's say you host a project called `foobar`. This project also has some kind of web presence (not necessarily a full grown website). You want to allow people who are interested in `foobar` to contact you. Therefore you would like to leave an email address. On the other hand you would like to avoid to be spammed. This would be a reason not to leave an email address.

The solution is to have a server (maybe inbucket) filtering the mail: if the email title contains the word `foobar` the mail should be forwarded. Otherwise it should be deleted (maybe after some incubation time).

At the same time you would tell the visitors of your web presence to use `foobar` in the title or even make a `mailto:` link like this `mailto:address@domain.tld?subject=foobar`.

**Comment by jhillyerd** [comment]
The intent of Inbucket is to give developers a safe environment to develop and test their applications in.  Forwarding adds an element of danger if Inbucket ends up mis-configured.  This has been borne out in production environments where engineers accused Inbucket of sending an email to a CxO.  It's easy to win that argument when it's not possible.

You might want to take a look at [Sieve](https://en.wikipedia.org/wiki/Sieve_(mail_filtering_language)) - you could pull mail from Inbucket via POP3 or REST and have Sieve decide what to do with it.

That being said, if a rules language is ever implemented for #52, we might allow it to do conditional mail forwarding - but that is likely years away.
