### ISSUE TITLE
Concurrency issues

### ISSUE THREAD

**Issue by makarchuk** [jhillyerd/inbucket#77]
Inbucket seems to handle poorly multiple emails receiving:

my test python script: 
```
from multiprocessing.pool import ThreadPool
import requests
import time

p = ThreadPool(500)

eml = """
To: test@test.com
From: Empty <empty@example.net>
Subject: Empty message
Message-ID: <7ced65ff-46e2-9ae2-e589-237ab9201078@example.net>
Date: Fri, 10 Nov 2017 15:09:34 +0300
X-Mozilla-Draft-Info: internal/draft; vcard=0; receipt=0; DSN=0; uuencode=0;
 attachmentreminder=0; deliveryformat=4
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101
 Thunderbird/52.4.0
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Language: en-US
Content-Transfer-Encoding: 7bit

Some text
"""

def send(i):   
    import smtplib                                                       
    cli = smtplib.SMTP('localhost', port=10025)                     
    cli.sendmail('test@test.com', ['test@test.com'], eml)

requests.delete('http://localhost:10080/api/v1/mailbox/test')
print("mailbox size after purge: {}".format(len(requests.get('http://localhost:10080/api/v1/mailbox/test').json())))
time.sleep(1)
p.map(send, range(1000))
time.sleep(1)
print("mailbox size after send: {}".format(len(requests.get('http://localhost:10080/api/v1/mailbox/test').json())))
```

Excpected: result:
```
mailbox size after purge: 0
mailbox size after send: 1000
```

Actual result:
```
mailbox size after purge: 0
mailbox size after send: %MUCH LOWER NUMBER%
```
Number of emails I see is usually around 20-50, but it differs from run to run

My inbucket config: 
```
# inbucket.conf
# Configuration for Inbucket inside of Docker
#
# These should be reasonable defaults for a production install of Inbucket

#############################################################################
[DEFAULT]

# Not used directly, but is typically referenced below in %()s format.
install.dir=/opt/inbucket
default.domain=inbucket.local

#############################################################################
[logging]

# Options from least to most verbose: ERROR, WARN, INFO, TRACE
level=INFO

#############################################################################
[smtp]

# IPv4 address to listen for SMTP connections on.
ip4.address=0.0.0.0

# IPv4 port to listen for SMTP connections on.
ip4.port=10025

# used in SMTP greeting
domain=%(default.domain)s

# optional: mail sent to accounts at this domain will not be stored,
# for mixed use (content and load testing)
domain.nostore=bitbucket.local

# Maximum number of RCPT TO: addresses we allow from clients, the SMTP
# RFC recommends this be at least 100.
max.recipients=100

# How long we allow a network connection to be idle before hanging up on the
# client, SMTP RFC recommends at least 5 minutes (300 seconds).
max.idle.seconds=300

# Maximum allowable size of message body in bytes (including attachments)
max.message.bytes=20480000

# Should we place messages into the datastore, or just throw them away
# (for load testing): true or false
store.messages=true

#############################################################################
[pop3]

# IPv4 address to listen for POP3 connections on.
ip4.address=0.0.0.0

# IPv4 port to listen for POP3 connections on.
ip4.port=10110

# used in POP3 greeting
domain=%(default.domain)s

# How long we allow a network connection to be idle before hanging up on the
# client, POP3 RFC requires at least 10 minutes (600 seconds).
max.idle.seconds=600

#############################################################################
[web]

# IPv4 address to serve HTTP web interface on
ip4.address=0.0.0.0

# IPv4 port to serve HTTP web interface on
ip4.port=10080

# Name of web theme to use
theme=bootstrap

# Prompt displayed between the mailbox entry field and View button. Leave
# empty or comment out to hide the prompt.
mailbox.prompt=@inbucket

# Path to the selected themes template files
template.dir=%(install.dir)s/themes/%(theme)s/templates

# Should we cache parsed templates (set to false during theme dev)
template.cache=true

# Path to the selected themes public (static) files
public.dir=%(install.dir)s/themes/%(theme)s/public

# Path to the greeting HTML displayed on front page, can be moved out of
# installation dir for customization
greeting.file=/con/configuration/greeting.html

# Key used to sign session cookie data so that it cannot be tampered with.
# If this is left unset, Inbucket will generate a random key at startup
# and previous sessions will be invalidated.
#cookie.auth.key=secret-inbucket-session-cookie-key

# Enable or disable the live message monitor tab for the web UI. This will let
# anybody see all messages delivered to Inbucket.  This setting has no impact
# on the availability of the underlying WebSocket.
monitor.visible=true

# How many historical message headers should be cached for display by new
# monitor connections.  It does not limit the number of messages displayed by
# the browser once the monitor is open; all freshly received messages will be
# appended to the on screen list.  This setting also affects the underlying
# API/WebSocket.
monitor.history=30

#############################################################################
[datastore]

# Path to the datastore, mail will be written into subdirectories
path=/con/data

# How many minutes after receipt should a message be stored until it's
# automatically purged.  To retain messages until manually deleted, set this
# to 0
retention.minutes=4320

# How many milliseconds to sleep after purging messages from a mailbox.
# This should help reduce disk I/O when there are a large number of messages
# to purge.
retention.sleep.millis=100

# Maximum number of messages we will store in a single mailbox. If this
# number is exceeded, the oldest message in the box will be deleted each
# time a new message is received for it.
mailbox.message.cap=3000
```

All emails seem to be present in `/con/data/mail/a94/a94a8f/a94a8fe5ccb19ba61c4c0873d391e987982fbbd3/` folder they are just missing in index.

Any help is much appreciated

**Comment by makarchuk** [comment]
Checked this for `master` branch and `v1.2.0` tag

**Comment by jhillyerd** [comment]
Thanks for reporting this (with the test code) and sending the CL!  I'm traveling, so it may be a week before I can approve, I want to better understand where this is failing.

**Comment by makarchuk** [comment]
As far as I understood it, each goroutine separately loads mailbox from disk, apply changes and dump on disk. My fix is a bit hacky (I'm using it on my test now, though). I have a global lock, so every goroutine locks delivery process for every other while it loads mailbox, apply changes and dumps it back on disk. It's obviously slow solution.

I personally think it would be better to use global state shared among all goroutines for this. I'll try to dedicate some time to it in a next few days.

**Comment by jhillyerd** [comment]
Your description makes sense.  When I started writing Inbucket, I considered that a lock-per-mailbox would be the best thing, just more work to implement.  Perhaps a hashtable of a mutex per mailbox.  That wouldn't improve performance much in the case where all the mail is going to a single inbox, so global state could help there - but I wouldn't recommend spending time one that (see plans below).

For mutexes or global state, we do need to make sure that there is only once instance of the filestore being used for all of Inbucket.  It used to be that each service (smtpd, pop3d, httpd) would instantiate its own.  Sloppy, I know! Inbucket was my first non-hello-world Go program, I was focused on making it work at all, cut me some slack. ;)

Longer term, my plan:
1. Refactor datastore.Message to make it easier to implement alternate stores #69 
2. Implement an in-memory only store.  I imagine this would be good for desktop developers, and inbuckets stood up as part of a single CI build.
3. Implement a store on top of embedded database, such as BoltDB and [Storm](https://github.com/asdine/storm).  This should make operations that need to walk mailboxes much faster, and probably give us concurrency for free.

More roadmap type stuff here: https://github.com/jhillyerd/inbucket/projects/1

**Comment by makarchuk** [comment]
Memory-only state sounds amazing (i would totally use it in my testing).

**Comment by jhillyerd** [comment]
I've been mulling this over...  regardless of what sort of data store Inbucket uses in the future, if we are to maintain a general Mailbox+Message interface, locking will be required to prevent this issue.

As you noted, the current design does not have any shared mailbox state between threads.  At minimum, locks would have to be shared to be effective.  Two approaches come to mind:

## Shared locks

Maintaining a lock per mailbox would get messy, there would have to some sort of LRU cache that would cleanup unused locks. When researching lock data structures, I found some inspiration in [keymutex](https://github.com/neverlee/keymutex); although I'd prefer to implement from scratch rather than import this.  The basic idea would be that we use the first byte or two of the mailbox hash to select one lock from a mutex array of len 2^8 or 2^16.  This would allow for much more concurrency than a single mutex, but prevent growth over time.

## LRU cache for Mailboxes

Cache most recently used mailbox instances, and have each mailbox contain a mutex.  More complex, but would likely improve performance.  We would still need to make sure no mailbox got evicted from the cache while it was locked, as that could allow concurrent writes.  [ccache](https://github.com/karlseguin/ccache) looks like it would work well in this case, as its tracking feature would prevent active mailboxes from being evicted.

**Comment by jhillyerd** [comment]
For the shared lock scenario, it's critical that code obtaining a mailbox declare its intent up front (RO or RW), otherwise this same race condition could still happen causing an incomplete index to be written.

For the LRU scenario, I'm not sure.  Mutexes could be upgraded on the fly, but I'd expect that to lead to deadlocks.  Probably both would need to declare intent prior to obtaining the mailbox.

**Comment by makarchuk** [comment]
I feel like this is the moment where it would be propper to come up with concise interface for `Store` and move from there.


In my opinion it should be something like `Repository` pattern. We hold one global object to access all the data. In this case this object can actually hold `mailbox` in memory and only lock it while specific operations are being executed. And it'll be even possible (and quite easy) to drop mailbox out of memory if it hasn't been accessed for a while.

Also a bit related question. Is `Mailbox` entity is really that useful? If you intent to keep it it'll only make alternative `Store`s harder to implement, since you would also need to implement `Mailbox`. As an alternative: `Mailbox` may only be able to access actual data by calling to `Store`, not manipulate it.


I see this somewhat like this
```
type Store interface() {
    GetMailbox(string) (Mailbox, error)
    RemoveMailbox(string) (Message, error)
    GetMessage(string, int) (Message, error)
    RemoveMessage(string, int) (Message, error)
    GetMessage(string, int) (Message, error)
    AddMessage(string, (Message, error)
}
```
`Mailbox` only represents set of `Message`s it may even be literally defined as  `type Mailbox []Message`, and only used to make it clearer to work in with `Mailbox`es in web and `POP`/`IMAP`.

As for locking: `keymutex`-like thing would be nice.

Sorry if what I'm saying is a bit unclear I'm having some troubles describing my ideas right now.

**Comment by jhillyerd** [comment]
Yes, I think this is a good idea.  Getting rid of Mailbox, and requiring all mutation calls to be made on the central Store interface would allow the Store implementation to hide any required locking or caching from client code.  We should continue this in #69.

I think using a keymutex style lock at message delivery and message delete is the quick and dirty fix for this bug.

**Comment by jhillyerd** [comment]
I've got an ugly fix checked into the develop branch.  Your python now shows 1000 messages when I run it locally, let me know if it works for you and I'll release it.

**Comment by makarchuk** [comment]
It works fine for me

**Comment by jhillyerd** [comment]
Thanks for testing!  I've started a branch to work on the Storage revamp, you can follow along in #69
